# Generated by Django 4.2.1 on 2023-06-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=55)),
                ('company_work', models.CharField(max_length=55)),
                ('company_id', models.IntegerField()),
                ('company_location', models.CharField(max_length=55)),
            ],
        ),
    ]
