# Generated by Django 4.2.1 on 2023-06-13 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('06d6d879-3e9b-4354-b336-42119dd48202'), editable=False, primary_key=True, serialize=False),
        ),
    ]
